package com.example.wordquiz;


class EnglishWords {
    private String[][] words;

    EnglishWords(int level) {
        switch (level) {
            case 1:
                words = levelEasy();
                break;
            case 2:
                words = levelMedium();
                break;
            case 3:
                words = levelHard();
                break;
        }

    }

//    private String[][] levelEasy() {
//        return new String[][]{
//                {"Ahead", "Önce"},
//                {"Belongings", "Kişisel Eşya"},
//                {"Information", "Bilgi"},
//                {"Possessions", "Sahiplik"},
//                {"Studying Abroad", "Yurtdışında Eğitim"},
//                {"Abroad", "Yurt Dışı"},
//                {"Study", "Çalışmak"},
//                {"Husband", "Eş (Erkek)"},
//                {"Wife", "Eş (Kadın)"},
//                {"Retired", "Emekli"},
//                {"Engineer", "Mühendis"},
//                {"Taxi Driver", "Taksici"},
//                {"Driver", "Sürücü"},
//                {"Winter", "Kış"},
//                {"Moved", "Taşımak"},
//                {"Greet", "Selam"},
//                {"Conversation", "Konuşma"},
//                {"Gardener", "Bahçıvan"},
//                {"Direction", "Yönler"},
//                {"Clue", "İpucu"},
//                {"Someone", "Birisi"},
//                {"Towel", "Havlu"},
//                {"Suitcase", "Bavul"},
//                {"Anxious", "Endişeli"},
//                {"Pleasure", "Zevk"},
//
//                {"Theme", "Tema"},
//                {"Cellar", "Kiler"},
//                {"Coin", "Madeni Para"},
//                {"Facility", "Tesis"},
//                {"Fairly", "Oldukça"},
//                {"Fountain", "Çeşme"},
//                {"Go Ahead", "Devam Etmek"},
//                {"Indoor", "Kapalı"},
//                {"Mayor", "Belediye Başkanı"},
//                {"Neat", "Temiz"},
//                {"Neighbouring", "Komşu"},
//                {"Overlook", "Bakmak"},
//                {"Pedestrian", "Yaya"},
//                {"Powerful", "Güçlü"},
//                {"Shopping", "Alışveriş"},
//                {"Treat", "Tedavi Etmek"},
//                {"Unfortunately", "Maalesef"},
//                {"Environment", "Çevre"},
//                {"Baker", "Fırıncı"},
//                {"Bakery", "Fırın"},
//                {"Butcher", "Kasap"},
//                {"Chemist", "Eczane"},
//                {"Newsagent", "Gazete Bayi"},
//                {"Shopping Mall", "Alışveriş Merkezi"},
//                {"Hospital", "Hastane"},
//                {"Grocery", "Market"},
//                {"Library", "Kütüphane"},
//                {"Clothes MissionPage", "Giyim Mağazası"},
//                {"Clothes", "Giyim"},
//                {"Describe", "Tanımlamak"},
//                {"Compare", "Kıyaslamak"},
//                {"Latest", "En Son"},
//                {"Square", "Meydan"},
//                {"Statue", "Heykelcilik"},
//                {"Stand", "Duruş"},
//                {"Middle", "Orta"},
//                {"Pound", "Havuz"},
//                {"Townspeople", "Şehir Halkı"},
//                {"Fairly", "Oldukça"},
//                {"Equally", "Eşit Olarak"},
//                {"View", "Görünüm"},
//                {"Opposite", "Karşıda"},
//                {"Corner", "Köşe"},
//                {"Drove", "Kalabalık"},
//                {"Crime", "Suç"},
//                {"Wardrobe", "Dolap"},
//                {"Beat", "Yenmek"},
//                {"Seat", "Koltuk"},
//                {"Cheap", "Ucuz"},
//                {"Feet", "Ayaklar"},
//                {"Foot", "Ayak"},
//                {"Green", "Yeşil"},
//                {"Eat", "Yemek"},
//                {"Steal", "Çalmak"},
//                {"Heal", "İyileşmek"},
//                {"Sit", "Oturmak"},
//                {"Chip", "Fiş"},
//                {"Fit", "Uydurmak"},
//                {"Grin", "Gülümseme"},
//                {"It", "O"},
//                {"Still", "Hala"},
//                {"Hill", "Tepe"},
//                {"Dip", "Daldırmak"},
//                {"Fill", "Doldurmak"},
//                {"Previous", "Önceki"},
//                {"Heap", "Yığın"},
//                {"Live", "Yaşamak"},
//                {"These", "Bunlar"},
//                {"List", "Liste"},
//                {"Deep", "Derin"},
//                {"Feel", "Hissetmek"},
//                {"Hip", "Kalça"},
//                {"Leave", "Ayrılmak"},
//                {"This", "Bu"},
//                {"Least", "En Az"},
//        };
//    }

    private String[][] levelEasy() {
        return new String[][]{
                //1 Seviye
                {"Accountant", "Muhasebeci"},
                {"Afraid", "Korkmak"},
                {"Age", "Yaş"},
                {"Alone", "Yalnız"},
                {"Airplane", "Uçak"},
                {"Angry", "Kızgın"},
                {"Animal", "Hayvan"},
                {"Answer", "Cevap"},
                {"Architect", "Mimar"},
                {"Arrive", "Varmak"},
                {"Aunt", "Hala"},
                {"Bag", "Çanta"},
                {"Ball", "Top"},
                {"Bath", "Banyo"},
                {"Beautiful", "Güzel"},

                //2 Seviye
                {"Bill", "Fatura"},
                {"Body", "Vücut"},
                {"Boil", "Kaynamak"},
                {"Bookstore", "Kitapevi"},
                {"Boring", "Sıkıcı"},
                {"Borrow", "Borç Almak"},
                {"Boss", "Patron"},
                {"Bottle", "Şişe"},
                {"Box", "Kutu"},
                {"Brave", "Cesur"},
                {"Bread", "Ekmek"},
                {"Break", "Kırmak"},
                {"Bridge", "Köprü"},
                {"Brush", "Fırça"},
                {"Build", "İnşa Etmek"},

                //3 Seviye
                {"Butter", "Tere Yağ"},
                {"Calculator", "Hesap Makinesi"},
                {"Calendar", "Takvim"},
                {"Call", "Aramak"},
                {"Capital", "Sermaye"},
                {"Carpenter", "Marangoz"},
                {"Carpet", "Halı"},
                {"Carry", "Taşımak"},
                {"Cartoon", "Çizgi Film"},
                {"Chair", "Sandalye"},
                {"Cheap", "Ucuz"},
                {"Cheese", "Peynir"},
                {"Cherry", "Kiraz"},
                {"Chicken", "Piliç"},
                {"Church", "Kilise"},

                //4 Seviye
                {"Clean", "Temiz"},
                {"Clear", "Açık"},
                {"Clever", "Zeki"},
                {"Clock", "Saat"},
                {"Cloud", "Bulut"},
                {"Coat", "Ceket"},
                {"Cold", "Soğuk"},
                {"Company", "Şirket"},
                {"Continue", "Devam Etmek"},
                {"Correct", "Doğru"},
                {"Country", "Ülke"},
                {"Cow", "İnek"},
                {"Cry", "Ağlamak"},
                {"Daily", "Günlük"},
                {"Dark", "Koyu"},

                //5 Seviye
                {"Dentist", "Dişçi"},
                {"Difficult", "Zor"},
                {"Dirty", "Pis"},
                {"Divorced", "Boşanmış"},
                {"Draw", "Çizmek"},
                {"Early", "Erken"},
                {"Earn", "Para Kazanmak"},
                {"Elephant", "Fil"},
                {"Emergency", "Tehlike"},
                {"Empty", "Boş"},
                {"Engaged", "Nişanlı"},
                {"Engineer", "Mühendis"},
                {"Enough", "Yeterli"},
                {"Eraser", "Silgi"},
                {"Error", "Hata"},

                //6 Seviye
                {"Fall", "Düşmek"},
                {"Far", "Uzak"},
                {"Farm", "Tarla"},
                {"Fat", "Şişman"},
                {"Finger", "Parmak"},
                {"Fire", "Ateş"},
                {"Flight", "Uçuş"},
                {"Floor", "Kat"},
                {"Fork", "Çatal"},
                {"Friendly", "Arkadaş Canlısı"},
                {"Fruit", "Meyve"},
                {"Funny", "Eğlenceli"},
                {"Garden", "Bahçe"},
                {"Glass", "Bardak"},
                {"Grape", "Üzüm"},

                //7 Seviye
                {"Gun", "Silah"},
                {"Habit", "Alışkanlık"},
                {"Half", "Yarım"},
                {"Hand", "El"},
                {"Handsome", "Yakışıklı"},
                {"Hate", "Nefret Etmek"},
                {"Health", "Sağlıklı"},
                {"Hear", "Duymak"},
                {"Heart", "Kalp"},
                {"High", "Yüksek"},
                {"History", "Tarih"},
                {"Horror", "Korku"},
                {"Hungry", "Acıkmış Olmak"},
                {"Ill", "Hasta Olmak"},
                {"Interested", "İlgili"},

                //8 Seviye
                {"Job", "İş"},
                {"Journalist", "Gazeteci"},
                {"Kill", "Öldürmek"},
                {"Large", "Büyük"},
                {"Laugh", "Gülmek"},
                {"Lawyer", "Avukat"},
                {"Leave", "Ayrılmak"},
                {"Left", "Sol"},
                {"Lend", "Ödünç Vermek"},
                {"Letter", "Mektup"},
                {"Library", "Kütüphane"},
                {"Light", "Işık"},
                {"Lunch", "Öğle Yemeği"},
                {"Manager", "Yönetici"},
                {"Main", "Ana"},

                //9 Seviye
                {"Map", "Harita"},
                {"Married", "Evli"},
                {"Meal", "Yemek"},
                {"Meet", "Tanışmak"},
                {"Meeting", "Toplantı"},
                {"Melon", "Kavun"},
                {"Minute", "Dakika"},
                {"Mirror", "Ayna"},
                {"Miss", "Özlemek"},
                {"Mistake", "Hata"},
                {"Month", "Ay"},
                {"Need", "İhtiyacı Olmak"},
                {"Neighbor", "Komşu"},
                {"News", "Haber"},
                {"Nice", "Hoş"},

                //10 Seviye
                {"Nose", "Burun"},
                {"Nurse", "Hemşire"},
                {"Object", "Nesne"},
                {"Opposite", "Karşıda"},
                {"Oven", "Fırın"},
                {"Page", "Sayfa"},
                {"Paint", "Resim Yapmak"},
                {"Parent", "Ebeveyn"},
                {"Pass", "Geçiş"},
                {"Pay", "Ödemek"},
                {"Pepper", "Biber"},
                {"Personal", "Kişisel"},
                {"Pet", "Evcil Hayvan"},
                {"Place", "Yer"},
                {"Plane", "Uçak"},

                //11 Seviye
                {"Pocket", "Cep"},
                {"Polite", "Kibar"},
                {"Pool", "Havuz"},
                {"Poor", "Fakir"},
                {"Possible", "Mümkün"},
                {"Push", "İtmek"},
                {"Quick", "Çabuk"},
                {"Quiet", "Sessiz"},
                {"Railway", "Demiryolu"},
                {"Ready", "Hazır"},
                {"Refrigerator", "Buzdolabı"},
                {"Remember", "Hatırlamak"},
                {"Rent", "Kiralamak"},
                {"Repair", "Tamir Etmek"},
                {"Repeat", "Tekrarlamak"},

                //12 Seviye
                {"Restroom", "Tuvalet"},
                {"Return", "Geri Dönmek"},
                {"Rice", "Pirinç"},
                {"Rich", "Zengin"},
                {"Ride", "Sürmek"},
                {"Right", "Sağ"},
                {"Ring", "Çalmak"},
                {"Rise", "Yükselmek"},
                {"River", "Nehir"},
                {"Road", "Yol"},
                {"Roof", "Çatı"},
                {"Room", "Oda"},
                {"Rose", "Gül"},
                {"Salt", "Tuz"},
                {"Same", "Aynı"},

                //13 Seviye
                {"Security", "Güvenlik"},
                {"Sell", "Satmak"},
                {"Serious", "Ciddi"},
                {"Shelf", "Raf"},
                {"Ship", "Gemi"},
                {"Shirt", "Gömlek"},
                {"Shoe", "Ayakkabı"},
                {"Show", "Göstermek"},
                {"Sick", "Hasta"},
                {"Sing", "Şarkı Söylemek"},
                {"Single", "Bekar"},
                {"Skirt", "Etek"},
                {"Sky", "Gökyüzü"},
                {"Smile", "Gülümsemek"},
                {"Snow", "Kar"},

                //14 Seviye
                {"Socks", "Çorap"},
                {"Son", "Oğul"},
                {"Song", "Şarkı"},
                {"Spend", "Harcamak"},
                {"Spoon", "Kaşık"},
                {"Stamp", "Pul"},
                {"Stay", "Kalmak"},
                {"Story", "Hikaye"},
                {"Strawberry", "Çilek"},
                {"Strong", "Güçlü"},
                {"Successful", "Başarılı"},
                {"Suit", "Takım Elbise"},
                {"Sweet", "Tatlı"},
                {"Talk", "Konuşmak"},
                {"Tall", "Uzun"},

                //15 Seviye
                {"Teach", "Öğretmek"},
                {"Thick", "Kalın"},
                {"Thief", "Hırsız"},
                {"Thin", "İnce"},
                {"Think", "Füşünmek"},
                {"Thirsty", "Susamak"},
                {"Ticket", "Bilet"},
                {"Tidy", "Düzenli"},
                {"Tired", "Yorulmuş Olmak"},
                {"Toothbrush", "Diş Fırçası"},
                {"Toothpaste", "Diş Macunu"},
                {"Towel", "Havlu"},
                {"Tower", "Kule"},
                {"Town", "Şehir"},
                {"Toy", "Oyuncak"},

                //16 Seviye
                {"Trainers", "Spor Ayakkabısı"},
                {"Travel", "Seyehat"},
                {"Tree", "Ağaç"},
                {"Trousers", "Pantolon"},
                {"Turn", "Dönmek"},
                {"Ugly", "Çirkin"},
                {"Umbrella", "Şemsiye"},
                {"Uncle", "Amca"},
                {"Understand", "Anlamak"},
                {"Underwear", "İç Çamaşır"},
                {"Waiter", "Garson"},
                {"Wall", "Duvar"},
                {"Watermelon", "Karpuz"},
                {"Way", "Yön"},
                {"Weak", "Güçsüz"},

                //17 Seviye
                {"Wear", "Giyinmek"},
                {"Week", "Hafta"},
                {"Wind", "Rüzgar"},
                {"Winter", "Kış"},
                {"Wonderful", "Mükemmel"},
                {"Word", "Kelime"},
                {"Wrong", "Yanlış"},
                {"Zoo", "Hayvanat Bahçesi"},
                {"Abroad", "Yurt Dışına"},
                {"Accept", "Kabullenmek"},
                {"Accident", "Kaza Yapmak"},
                {"Adventure", "Macera"},
                {"Agree", "Katılmak"},
                {"Anniversary", "Yıllık"},
                {"Ant", "Karınca"},

                //18 Seviye
                {"Area", "Alan"},
                {"Argue", "Tartışmak"},
                {"Arm", "Kol"},
                {"Backgammon", "Tavla"},
                {"Begin", "Başlamak"},
                {"Believe", "İnanmak"},
                {"Bell", "Zil"},
                {"Bite", "Isırmak"},
                {"Blanket", "Battaniye"},
                {"Brain", "Beyin"},
                {"Bring", "Getirmek"},
                {"Business", "İş"},
                {"Busy", "Meşgul"},
                {"Cable", "Kablo"},
                {"Can", "E Bilmek"},

                //19 Seviye
                {"Cap", "Şapka"},
                {"Cash", "Nakit"},
                {"Catch", "Yakalamak"},
                {"Change", "Değiştirmek"},
                {"Changing Room", "Giyinme Kabini"},
                {"Chess", "Satranç"},
                {"Chewing Gum", "Sakız"},
                {"Chin", "Çene"},
                {"Choose", "Seçmek"},
                {"Climb", "Tırmanmak"},
                {"Cloth", "Giyisi"},
                {"Collect", "Toplamak"},
                {"Complete", "Tamamlamak"},
                {"Confused", "Aklı Karışmak"},
                {"Connect", "Bağlanmak"},

                //20 Seviye
                {"Contact", "Bağlantı"},
                {"Cookie", "Kurabiye"},
                {"Cool", "Rahat"},
                {"Cost", "Maliyet"},
                {"Cotton", "Pamuk"},
                {"Couch", "Antrenör"},
                {"Cough", "Öksürmek"},
                {"Crazy", "Çılgın"},
                {"Curious", "Meraklı"},
                {"Customer", "Müşteri"},
                {"Cut", "Kesmek"},
                {"Cute", "Şirin"},
                {"Dangerous", "Tehlikeli"},
                {"Dead", "Ölü"},
                {"Decide", "Karar Vermek"},
        };
    }

    private String[][] levelMedium() {
        return new String[][]{
                //21 Seviye
                {"Deep", "Derin"},
                {"Delete", "Silmek"},
                {"Delicious", "Lezzetli"},
                {"Describe", "Tanımlamak"},
                {"Diamond", "Elmas"},
                {"Die", "Ölmek"},
                {"Direction", "Yön"},
                {"Discover", "Keşfetmek"},
                {"Discuss", "Tartışmak"},
                {"Disturb", "Rahatsız Etmek"},
                {"Drawer", "Çekmece"},
                {"Dream", "Rüya"},
                {"Earring", "Küpe"},
                {"Elbow", "Dirsek"},
                {"Elevator", "Asansör"},

                //22 Seviye
                {"Enjoy", "Hoşlanmak"},
                {"Entertainment", "Gösteri"},
                {"Equal", "Eşit"},
                {"Escape", "Kaçmak"},
                {"Excellent", "Mükemmel"},
                {"Exhausted", "Yorgun Olmak"},
                {"Expensive", "Pahalı"},
                {"Experience", "Tecrübe"},
                {"Explain", "Açıklamak"},
                {"Eyebrow", "Kaş"},
                {"Eyelash", "Kirpik"},
                {"Eyelid", "Göz Kapağı"},
                {"Face", "Yüz"},
                {"Factory", "Fabrika"},
                {"Fail", "Başarısız Olmak"},

                //23 Seviye
                {"Famous", "Ünlü"},
                {"Fan", "Fan"},
                {"Feel", "Hissetmek"},
                {"Female", "Bayan"},
                {"Fight", "Dövüşmek"},
                {"Fill", "Doldurmak"},
                {"First Aid", "İlk Yardım"},
                {"Flag", "Bayrak"},
                {"Flat", "Düz"},
                {"Flour", "Un"},
                {"Fog", "Sis"},
                {"Follow", "Takip Etmek"},
                {"Food", "Yiyecek"},
                {"Foreign", "Yabancı"},
                {"Formal", "Resmi"},

                //24 Seviye
                {"Fresh", "Ferah"},
                {"Front", "Ön"},
                {"Fuel", "Yakıt"},
                {"Furniture", "Mobilya"},
                {"Future", "Gelecek"},
                {"Garlic", "Sarımsak"},
                {"Gate", "Kapı"},
                {"Generous", "Cömert"},
                {"Gift", "Hediye"},
                {"Glad", "Memnun Olmak"},
                {"Glove", "Eldiven"},
                {"Graduate", "Mezun Olmak"},
                {"Grass", "Çim"},
                {"Grocer", "Süpermarket"},
                {"Grow", "Büyümek"},

                //25 Seviye
                {"Guide", "Rehber"},
                {"Hard", "Zor"},
                {"Harmful", "Zararlı"},
                {"Huge", "Devasa"},
                {"Idea", "Fikir"},
                {"Impossible", "İmkansız"},
                {"Insect", "Böcek"},
                {"Intelligent", "Akıllı"},
                {"Introduce", "Tanıtmak"},
                {"Invite", "Davet Etmek"},
                {"Island", "Ada"},
                {"Jam", "Reçel"},
                {"Jar", "Kavanoz"},
                {"Join", "Katılmak"},
                {"Joke", "Şaka"},

                //26 Seviye
                {"Journey", "Seyehat"},
                {"Juice", "Meyve Suyu"},
                {"Jump", "Zıplamak"},
                {"Key", "Anahtar"},
                {"Kick", "Tekme"},
                {"Kind", "Tür"},
                {"Knee", "Diz"},
                {"Knife", "Bıçak"},
                {"Lake", "Göl"},
                {"Lamb", "Kuzu"},
                {"Leather", "Deri"},
                {"Leg", "Bacak"},
                {"Lift", "Kaldırmak"},
                {"Lip", "Dudak"},
                {"Lock", "Kilitlemek"},

                //27 Seviye
                {"Lose", "Kaybetmek"},
                {"Loud", "Yüksek Sesle"},
                {"Lovely", "Güzel"},
                {"Luck", "Şans"},
                {"Magic", "Sihir"},
                {"Mall", "Alışveriş Merkezi"},
                {"Medicine", "İlaç"},
                {"Mend", "Onarmak"},
                {"Mixed", "Karışık"},
                {"Monkey", "Maymun"},
                {"Moon", "Ay"},
                {"Mountain", "Dağ"},
                {"Mouth", "Ay"},
                {"Move", "Taşınmak"},
                {"Nail Clippers", "Tırnak Makası"},

                //28 Seviye
                {"Naughty", "Yaramaz"},
                {"Nervous", "Sinirli"},
                {"Noise", "Gürültü"},
                {"Novel", "Roman"},
                {"Ocean", "Okyanus"},
                {"Officier", "Memur"},
                {"Oil", "Yağ"},
                {"Overweight", "Kilolu"},
                {"Pick", "Seçmek"},
                {"Plant", "Bitki"},
                {"Plate", "Tabak"},
                {"Poem", "Şiir"},
                {"Point", "Nokta"},
                {"Power", "Güç"},
                {"Prepare", "Hazırlanmak"},

                //29 Seviye
                {"Pretty", "Sevimli"},
                {"Price", "Fiyat"},
                {"Produce", "Üretmek"},
                {"Queen", "Kraliçe"},
                {"Reach", "Ulaşmak"},
                {"Reason", "Sebep"},
                {"Record", "Kayıt"},
                {"Refuse", "Reddetmek"},
                {"Relation", "İlişki"},
                {"Relax", "Rahatlamak"},
                {"Remote Control", "Uzaktan Kontrol"},
                {"Reply", "Cevap"},
                {"Report", "Bildirmek"},
                {"Retire", "Emekli Olmak"},
                {"Rock", "Kaya"},

                //30 Seviye
                {"Rope", "İp"},
                {"Rude", "Kaba"},
                {"Rule", "Kural"},
                {"Safe", "Güvenli"},
                {"Salary", "Maaş"},
                {"Save", "Kaydetmek"},
                {"Scissors", "Makas"},
                {"Seat", "Koltuk"},
                {"Select", "Seçmek"},
                {"Send", "Göndermek"},
                {"Situation", "Durum"},
                {"Serve", "Hizmet Etmek"},
                {"Sharp", "Keskin"},
                {"Shine", "Parlamak"},
                {"Shoulder", "Omuz"},

                //31 Seviye
                {"Shout", "Bağırmak"},
                {"Sign", "İmza"},
                {"Silent", "Sessiz"},
                {"Simple", "Basit"},
                {"Ski", "Kayak"},
                {"Snake", "Yılan"},
                {"Soap", "Sabun"},
                {"Society", "Toplum"},
                {"Soft", "Yumuşak"},
                {"Spider", "Örümcek"},
                {"Stand", "Ayakta Durmak"},
                {"Stone", "Taş"},
                {"Storm", "Fırtına"},
                {"Subway", "Metro"},
                {"Sure", "Emin Olmak"},

                //32 Seviye
                {"Surprised", "Şaşırmak"},
                {"Tailor", "Terzi"},
                {"Taste", "Tat"},
                {"Team", "Takım"},
                {"Temperature", "Sıcaklık"},
                {"Tent", "Çadır"},
                {"Terrible", "Korkunç"},
                {"Throw", "Atmak"},
                {"Tiger", "Kaplan"},
                {"Tissue", "Doku"},
                {"Tongue", "Dil"},
                {"Touch", "Dokunmak"},
                {"Transport", "Nakletmek"},
                {"Trouble", "Sorun"},
                {"Try", "Denemek"},

                //33 Seviye
                {"Valuable", "Değerli"},
                {"Vegetable", "Bitki"},
                {"View", "Görüş"},
                {"Voice", "Ses"},
                {"War", "Savaş"},
                {"Warm", "Ilık"},
                {"Warning", "Uyarı"},
                {"Weather", "Hava"},
                {"Wet", "Islak"},
                {"Win", "Kazanmak"},
                {"Wine", "Şarap"},
                {"Worry", "Endişelenmek"},

                //34 Seviye
                {"Abroad", "Yurt Dışına"},
                {"Accept", "Kabuletmek"},
                {"Accident", "Kaza Yapmak"},
                {"Adventure", "Macera"},
                {"Agree", "Katılmak"},
                {"Anniversary", "Yıllık"},
                {"Ant", "Karınca"},
                {"Area", "Alan"},
                {"Argue", "Tartışmak"},
                {"Arm", "Kol"},
                {"Backgammon", "Tavla"},
                {"Begin", "Başlamak"},
                {"Believe", "İnanmak"},
                {"Bell", "Zil"},
                {"Bite", "Isırmak"},

                //35 Seviye
                {"Blanket", "Battaniye"},
                {"Brain", "Beyin"},
                {"Bring", "Getirmek"},
                {"Business", "İş"},
                {"Busy", "Meşgul"},
                {"Cable", "Kablo"},
                {"Can", "E Bilmek"},
                {"Cap", "Şapka"},
                {"Cash", "Nakit"},
                {"Catch", "Yakalamak"},
                {"Change", "Değiştirmek"},
                {"Changing Room", "Giyinme Kabini"},
                {"Chess", "Satranç"},
                {"Chewing Gum", "Sakız"},
                {"Chin", "Çene"},

                //36 Seviye
                {"Choose", "Seçmek"},
                {"Climb", "Tırmanmak"},
                {"Cloth", "Giyisi"},
                {"Collect", "Toplamak"},
                {"Complete", "Tamamlamak"},
                {"Confused", "Aklı Karışmak"},
                {"Connect", "Bağlanmak"},
                {"Contact", "Bağlantı"},
                {"Cookie", "Kurabiye"},
                {"Cool", "Rahat"},
                {"Cost", "Maliyet"},
                {"Cotton", "Pamuk"},
                {"Couch", "Antrenör"},
                {"Cough", "Öksürmek"},
                {"Crazy", "Çılgın"},

                //37 Seviye
                {"Curious", "Meraklı"},
                {"Customer", "Müşteri"},
                {"Cut", "Kesmek"},
                {"Cute", "Şirin"},
                {"Damage", "Zarar Vermek"},
                {"Dangerous", "Tehlikeli"},
                {"Dead", "Ölü"},
                {"Decide", "Karar Vermek"},
                {"Deep", "Derin"},
                {"Delete", "Silmek"},
                {"Delicious", "Lezzetli"},
                {"Describe", "Tanımlamak"},
                {"Diamond", "Elmas"},
                {"Die", "Ölmek"},
                {"Direction", "Yön"},

                //38 Seviye
                {"Discover", "Keşfetmek"},
                {"Discuss", "Tartışmak"},
                {"Disturb", "Rahatsız Etmek"},
                {"Drawer", "Çekmece"},
                {"Dream", "Rüya"},
                {"Earring", "Küpe"},
                {"Elbow", "Dirsek"},
                {"Elevator", "Asansör"},
                {"Enjoy", "Hoşlanmak"},
                {"Entertainment", "Gösteri"},
                {"Equal", "Eşit"},
                {"Escape", "Kaçmak"},
                {"Excellent", "Mükemmel"},
                {"Exhausted", "Yorgun Olmak"},
                {"Expensive", "Pahalı"},

                //39 Seviye
                {"Experience", "Tecrübe"},
                {"Explain", "Açıklamak"},
                {"Eyebrow", "Kaş"},
                {"Eyelash", "Kirpik"},
                {"Eyelid", "Göz Kapağı"},
                {"Face", "Yüz"},
                {"Factory", "Fabrika"},
                {"Fail", "Başarısız Olmak"},
                {"Famous", "Ünlü"},
                {"Fan", "Fan"},
                {"Feel", "Hissetmek"},
                {"Female", "Bayan"},
                {"Fight", "Dövüşmek"},
                {"Fill", "Doldurmak"},
                {"First Aid", "İlk Yardım"},

                //40 Seviye
                {"Flag", "Bayrak"},
                {"Flat", "Düz"},
                {"Flour", "Un"},
                {"Fog", "Sis"},
                {"Follow", "Takip Etmek"},
                {"Food", "Yiyecek"},
                {"Foreign", "Yabancı"},
                {"Formal", "Resmi"},
                {"Fresh", "Ferah"},
                {"Front", "Ön"},
                {"Fuel", "Yakıt"},
                {"Furniture", "Mobilya"},
                {"Future", "Gelecek"},
                {"Garlic", "Sarımsak"},
                {"Gate", "Kapı"},
        };
    }

    private String[][] levelHard() {
        return new String[][]{
                //41 Seviye
                {"Generous", "Cömert"},
                {"Gift", "Hediye"},
                {"Glad", "Memnun Olmak"},
                {"Glove", "Eldiven"},
                {"Graduate", "Mezun Olmak"},
                {"Grass", "Çim"},
                {"Grocer", "Süpermarket"},
                {"Grow", "Büyümek"},
                {"Guide", "Rehber"},
                {"Hard", "Zor"},
                {"Harmful", "Zararlı"},
                {"Huge", "Devasa"},
                {"Idea", "Fikir"},
                {"Impossible", "İmkansız"},
                {"Insect", "Böcek"},

                //42 Seviye
                {"Intelligent", "Akıllı"},
                {"Introduce", "Tanıtmak"},
                {"Invite", "Davet Etmek"},
                {"Island", "Ada"},
                {"Jam", "Reçel"},
                {"Jar", "Kavanoz"},
                {"Join", "Katılmak"},
                {"Joke", "Şaka"},
                {"Journey", "Seyehat"},
                {"Juice", "Meyve Suyu"},
                {"Jump", "Zıplamak"},
                {"Key", "Anahtar"},
                {"Kick", "Tekme"},
                {"Kind", "Tür"},
                {"Knee", "Diz"},

                //43 Seviye
                {"Knife", "Bıçak"},
                {"Lake", "Göl"},
                {"Lamb", "Kuzu"},
                {"Leather", "Deri"},
                {"Leg", "Bacak"},
                {"Lift", "Kaldırmak"},
                {"Lip", "Dudak"},
                {"Lock", "Kilitlemek"},
                {"Lose", "Kaybetmek"},
                {"Loud", "Yüksek Sesle"},
                {"Lovely", "Güzel"},
                {"Luck", "Şans"},
                {"Magic", "Sihir"},
                {"Mall", "Alışveriş Merkezi"},
                {"Meat", "Et"},

                //44 Seviye
                {"Medicine", "İlaç"},
                {"Mend", "Onarmak"},
                {"Mixed", "Karışık"},
                {"Monkey", "Maymun"},
                {"Moon", "Ay"},
                {"Mountain", "Dağ"},
                {"Mouth", "Ay"},
                {"Move", "Taşınmak"},
                {"Nail Clippers", "Tırnak Makası"},
                {"Naughty", "Yaramaz"},
                {"Nervous", "Sinirli"},
                {"Noise", "Gürültü"},
                {"Novel", "Roman"},
                {"Ocean", "Okyanus"},
                {"Officier", "Memur"},

                //45 Seviye
                {"Oil", "Yağ"},
                {"Overweight", "Kilolu"},
                {"Pick", "Seçmek"},
                {"Plant", "Bitki"},
                {"Plate", "Tabak"},
                {"Poem", "Şiir"},
                {"Point", "Nokta"},
                {"Power", "Güç"},
                {"Prepare", "Hazırlanmak"},
                {"Pretty", "Sevimli"},
                {"Price", "Fiyat"},
                {"Produce", "Üretmek"},
                {"Queen", "Kraliçe"},
                {"Reach", "Ulaşmak"},
                {"Reason", "Sebep"},

                //46 Seviye
                {"Record", "Kayıt"},
                {"Refuse", "Reddetmek"},
                {"Relation", "İlişki"},
                {"Relax", "Rahatlamak"},
                {"Remote Control", "Uzaktan Kontrol"},
                {"Reply", "Cevap"},
                {"Report", "Bildirmek"},
                {"Retire", "Emekli Olmak"},
                {"Rock", "Kaya"},
                {"Rope", "İp"},
                {"Rude", "Kaba"},
                {"Rule", "Kural"},
                {"Safe", "Güvenli"},
                {"Salary", "Maaş"},
                {"Save", "Kaydetmek"},

                //47 Seviye
                {"Scissors", "Makas"},
                {"Seat", "Koltuk"},
                {"Select", "Seçmek"},
                {"Send", "Göndermek"},
                {"Situation", "Durum"},
                {"Serve", "Hizmet Etmek"},
                {"Sharp", "Keskin"},
                {"Shine", "Parlamak"},
                {"Shoulder", "Omuz"},
                {"Shout", "Bağırmak"},
                {"Sign", "İmza"},
                {"Silent", "Sessiz"},
                {"Simple", "Basit"},
                {"Ski", "Kayak"},
                {"Snake", "Yılan"},

                //48 Seviye
                {"Soap", "Sabun"},
                {"Society", "Toplum"},
                {"Soft", "Yumuşak"},
                {"Spider", "Örümcek"},
                {"Stand", "Ayakta Durmak"},
                {"Stone", "Taş"},
                {"Storm", "Fırtına"},
                {"Subway", "Metro"},
                {"Sure", "Emin Olmak"},
                {"Surprised", "Şaşırmak"},
                {"Tailor", "Terzi"},
                {"Taste", "Tat"},
                {"Team", "Takım"},
                {"Temperature", "Sıcaklık"},
                {"Tent", "Çadır"},

                //49 Seviye
                {"Terrible", "Korkunç"},
                {"Throw", "Atmak"},
                {"Tiger", "Kaplan"},
                {"Tissue", "Doku"},
                {"Tongue", "Dil"},
                {"Touch", "Dokunmak"},
                {"Transport", "Nakletmek"},
                {"Trouble", "Sorun"},
                {"Try", "Denemek"},
                {"Usual", "Olağan"},
                {"Vacation", "Tatil"},
                {"Vacuum Cleaner", "Elektrikli Süpürge"},
                {"Valuable", "Değerli"},
                {"Vegetable", "Bitki"},
                {"View", "Görüş"},

                //50 Seviye
                {"Voice", "Ses"},
                {"War", "Savaş"},
                {"Warm", "Ilık"},
                {"Warning", "Uyarı"},
                {"Weather", "Hava"},
                {"Wet", "Islak"},
                {"Win", "Kazanmak"},
                {"Wine", "Şarap"},
                {"Worry", "Endişelenmek"},
                {"Account", "Hesap"},
                {"Accounts Payable", "Alacaklı Hesabı"},
                {"Accounts Receivable", "Senetsiz Alacak"},
                {"Accuse", "Suçlamak"},
                {"Achievement", "Kazanım"},
                {"Adjust", "Ayarlamak"},

                //51 Seviye
                {"Admit", "Kabul Etmek"},
                {"Advertise", "Reklam Etmek"},
                {"Advocate", "Avukat"},
                {"Affair", "Mesele"},
                {"Agreement", "Anlaşma"},
                {"Agriculture", "Tarım"},
                {"Aim", "Amaç"},
                {"Aisle", "Koridor"},
                {"Allowance", "Ödenek"},
                {"Ambassador", "Büyük Elçi"},
                {"Amusement", "Şaşırtıcı"},
                {"Ancient", "Tarihi"},
                {"Anticipate", "Beklemek"},
                {"Apparent", "Görünür"},
                {"Appearance", "Görünüş"},

                //52 Seviye
                {"Appreciate", "Takdir Etmek"},
                {"Appropriate", "Uygun"},
                {"Approve", "Onaylamak"},
                {"Argument", "Argüman"},
                {"Arrest", "Tutuklamak"},
                {"Audience", "Dinleyici"},
                {"Avoid", "Önlemek"},
                {"Baggage Claim", "Bagaj Teslim"},
                {"Balance Sheet", "Bilanço"},
                {"Bank Account", "Banka Hesabı"},
                {"Bankrupt", "İflas Etmek"},
                {"Bargain", "Pazarlık"},
                {"Beg", "Yalvarmak"},
                {"Beggar", "Dilenci"},
                {"Blame", "Suçlamak"},

                //53 Seviye
                {"Board Of Directors", "Yönetim Kurulu"},
                {"Breath", "Nefes"},
                {"Bribe", "Rüşvet"},
                {"Budget", "Bütçe"},
                {"Candidate", "Aday"},
                {"Cash Flow", "Nakit Akışı"},
                {"Cemetery", "Mezarlık"},
                {"Chamber Of Commerce", "Ticaret Odası"},
                {"Charming", "Çekici"},
                {"Chief Executive", "Başkan"},
                {"Circumstance", "Koşul"},
                {"Claim", "İddia Etmek"},
                {"Clerk", "Satıcı"},
                {"Client", "Müşteri"},
                {"Coal", "Kömür"},

                //54 Seviye
                {"Comment", "Yorum"},
                {"Commerce", "Ticaret"},
                {"Commercial", "Ticari"},
                {"Community", "Topluluk"},
                {"Competition", "Yarışma"},
                {"Complaint", "Şikayet"},
                {"Concentrate", "Konsantre Olmak"},
                {"Condition", "Şart"},
                {"Confess", "İtiraf Etmek"},
                {"Congratulate", "Tebrik Etmek"},
                {"Congress", "Kongre"},
                {"Consider", "Dikkate Almak"},
                {"Construction", "Yapı"},
                {"Consult", "Danışmak"},
                {"Contest", "Yarışma"},

                //55 Seviye
                {"Contribute", "Katkıda Bulunmak"},
                {"Convert", "Dönüştürmek"},
                {"Court", "Mahkeme"},
                {"Crossword", "Çapraz Bulmaca"},
                {"Cruel", "Zalim"},
                {"Customs", "Gümrük"},
                {"Dashboard", "Çamurluk"},
                {"Deadline", "Son Teslim Tarihi"},
                {"Deceive", "Aldatmak"},
                {"Declare", "İlan Etmeki"},
                {"Define", "Tanımlamak"},
                {"Deflation", "Sönme"},
                {"Depend", "Bağlı Olmak"},
                {"Desire", "İstemek"},
                {"Devaluation", "Değer Düşümü"},

                //56 Seviye
                {"Diagnose", "Tedavi"},
                {"Disappear", "Gözden Kaybolmak"},
                {"Disappoint", "Hayal Kırıklığına Uğramak"},
                {"Distance", "Uzaklık"},
                {"Distribution", "Dağıtım"},
                {"Dreadful", "Rezil"},
                {"Eager", "İstekli"},
                {"Election", "Seçim"},
                {"Embassy", "Büyükelçilik"},
                {"Encourage", "Cesaretlendirmek"},
                {"Enemy", "Düşman"},
                {"Enterprise", "Girişim"},
                {"Entrepreneur", "Girişimci"},
                {"Envy", "İmrenmek"},
                {"Essay", "Tecrübe Etmek"},

                //57 Seviye
                {"Establish", "Kurmak"},
                {"Estimate", "Tahmin Etmek"},
                {"Evaluate", "Değerlendirmek"},
                {"Evidence", "Kanıt"},
                {"Exaggerate", "Abartmak"},
                {"Examine", "İncelemek"},
                {"Exchange Rate", "Döviz Kuru"},
                {"Exhibition", "Sergi"},
                {"Experiment", "Deney"},
                {"Fame", "Söhret"},
                {"Fence", "Çit"},
                {"Fix", "Düzeltmek"},
                {"Fluent", "Akıcı"},
                {"Foolish", "Aptalca"},
                {"Forecast", "Tahmin Etmek"},

                //58 Seviye
                {"Fragile", "Kırılgan"},
                {"Frame", "Çerçeve"},
                {"Franchise", "Üyelik"},
                {"Frequent", "Sık"},
                {"Fund Raising", "Para Toplama"},
                {"Gamble", "Kumar"},
                {"Gear Transmission", "Aktarma Dişlileri"},
                {"Globalization", "Globelleşme"},
                {"Government", "Hükümet"},
                {"Grateful", "Minnettar"},
                {"Growth Rate", "Büyüme Oranı"},
                {"Hair Dryer", "Saç Kurutma Makinesi"},
                {"Harvest", "Hasat"},
                {"Hesitate", "Tereddüt Etmek"},
                {"Hire", "Kiralamak"},

                //59 Seviye
                {"Hitch Hike", "Otostop Çekmek"},
                {"Homesick", "Ev Hasreti Çeken"},
                {"Identification", "Kimlik Saptama"},
                {"In Advance", "Peşin"},
                {"Include", "İçermek"},
                {"Income", "Gelir"},
                {"Increase", "Artmak"},
                {"Independent", "Bağımsız"},
                {"Inflation", "Enflasyon"},
                {"Innocent", "Masum"},
                {"Inspection", "Denetleme"},
                {"Inspector", "Müfettiş"},
                {"Insurance", "Sigorta"},
                {"Interest Rate", "Faiz Oranı"},
                {"Invoice", "Fatura"},

                //60 Seviye
                {"Judge", "Yargıç"},
                {"Justice", "Adalet"},
                {"Kidnapping", "Kaçırmak"},
                {"Knowledge", "Bilgi"},
                {"Labor Force", "İş Gücü"},
                {"Landlord", "Ev Sahibi"},
                {"Licence Plate", "Ehliyet"},
                {"Life Vest", "Emniyet Kemeri"},
                {"Loan", "Kredi"},
                {"Loan Agreement", "Kredi Sözleşmesi"},
                {"Magnification", "Büyütme"},
                {"Maintain", "Bakım Yapmak"},
                {"Market Share", "Pazar Paylaşımı"},
                {"Marketing Research", "Pazar Araştırması"},
                {"Marvellous", "Harkulade"},

                //61 Seviye
                {"Massive", "Cüsseli"},
                {"Member Of Parliament", "Milletvekili"},
                {"Mention", "Bahsetmek"},
                {"Merchandise", "Ticaret Yapmak"},
                {"Nation", "Ulus"},
                {"Net Capital", "Net Sermaye"},
                {"Objective", "Objektif"},
                {"Observe", "Gözlemlemek"},
                {"Obvious", "Besbelli"},
                {"Opportunity", "Fırsat"},
                {"Participate", "Katılımcı"},
                {"Patience", "Sabır"},
                {"Percentage", "Yüzde"},
                {"Persuade", "İkna Etmek"},
                {"Pollution", "Kirlilik"},

                //62 Seviye
                {"Postpone", "Ertelemek"},
                {"President", "Baskan"},
                {"Price Control", "Fiyat Denetimi"},
                {"Prison", "Hapishane"},
                {"Process", "Süreç"},
                {"Profit", "Fayda"},
                {"Prohibit", "Hasaklamak"},
                {"Promotion", "Promosyon"},
                {"Property", "Mülk"},
                {"Proposal", "Teklif"},
                {"Prove", "Kanıtlamak"},
                {"Publicity", "Tanıtım"},
                {"Punctual", "Dakik"},
                {"Punishment", "Ceza"},
                {"Quantity", "Miktar"},

                //63 Seviye
                {"Quarrel", "Tartışmak"},
                {"Queue", "Sıraya Girmek"},
                {"Receipt", "Alındı"},
                {"Receive", "Teslim Almak"},
                {"Recognize", "Tanımak"},
                {"Recommend", "Önermek"},
                {"Reduce", "Eksiltmek"},
                {"Rub", "Sürtmek"},
                {"Schedule", "Program"},
                {"Regret", "Pişman Olmak"},
                {"Reject", "Reddetmek"},
                {"Release", "Serbest Bırakmak"},
                {"Religion", "Din"},
                {"Reluctant", "İsteksiz"},
                {"Rely", "Güvenmek"},

                //64 Seviye
                {"Represent", "Temsil Etmek"},
                {"Request", "Talep Etmek"},
                {"Resolution", "Kararlılık"},
                {"Resource", "Kaynak"},
                {"Respect", "Saygı"},
                {"Respond", "Yanıt Vermek"},
                {"Revenue", "Gelir"},
                {"Revise", "Gözden Geçirmek"},
                {"Sand", "Kum"},
                {"Science", "Bilim"},
                {"Seek", "Aramak"},
                {"Sense", "Algılamak"},
                {"Shake", "Sallamak"},
                {"Share", "Paylaşmak"},
                {"Sink", "Batmak"},

                //65 Seviye
                {"Skyscraper", "Gökdelen"},
                {"Steering Wheel", "Direksiyon Simidi"},
                {"Strike", "Vurmak"},
                {"Substitute", "Yerine Geçirmek"},
                {"Supplier", "Tedarikçi"},
                {"Suppose", "Sanmak"},
                {"Swear", "Küfür Etmek"},
                {"Take Action", "Harekete Geçmek"},
                {"Take Advantage", "Avantaj Elde Etmek"},
                {"Mission", "Görev"},
                {"Tax", "Vergi"},
                {"Throat", "Boğaz"},
                {"To Book", "Rezervasyon Yapmak"},
                {"Torture", "İşkence"},
                {"Trademark", "Ticari Marka"},

                //66 Seviye
                {"Transmit", "İletmek"},
                {"Treat", "Tedavi Etmek"},
                {"Treatment", "Tedavi"},
                {"Trick", "Kandırmak"},
                {"Underline", "Vurgulamak"},
                {"Unemployment", "İşsiz"},
                {"Urgent", "Acil"},
                {"Value Added Tax", "Katma Değer Vergisi"},
                {"Violent", "Şiddetli"},
                {"Volunteer", "Gönüllü Olmak"},
                {"Warehouse", "Depo"},
                {"Wealthy", "Zengin"},
                {"Weapon", "Silan"},
                {"Whistle", "Fısıldamak"},
                {"Wholesale", "Toptan Satış"},

                //67 Seviye
                {"Witness", "Tanık"},
                {"Zip", "Fermuar"},
                {"Gear", "Dişli"},
                {"Transmission", "İletim"},
        };
    }

    String[][] getWords() {
        return words;
    }
}
